User interaction
stefanleminh/ploot pull request #5
Opened 2020-10-07 19:17 UTC by stefanleminh

This pull requests adds the functionality of being able to move the users to the designated voice channels once a match starts or ends.

2020-10-17 17:58 UTC, AndreasMReumschuessel requested changes
Good work 👍! Just some minor things to imrove I'd say.
It is a bit confusing to handle the team lists and spectator lists instead of having a pool of players with attributes in which team they are and if they are spectator or not. But that's another story :D

2020-10-17 17:58 UTC, AndreasMReumschuessel commented on commands/randomize.js
> +  }
This check is popping up in almost every command. We should introduce a helper class for validation checks like these, so we avoid duplicate code and improve readability.
I'd think of something like
```
if(!isActiveSession(client)) {
   return;
}
```

2020-10-17 17:58 UTC, AndreasMReumschuessel commented on commands/endsession.js
>      client.sessionRunning = false;
Is this still in use? The session check is based on the `client.voiceChannels.length === 0` check and this variable is only set to false here and in index.js.

2020-10-17 18:18 UTC, stefanleminh commented on commands/endsession.js
>      client.sessionRunning = false;
You're right, the boolean one is not needed anymore, will be removed in the next commit.

2020-11-08 01:33 UTC, AndreasMReumschuessel approved these changes
Mixed feelings about this decision, but let's face it in another issue because I think we should have persistent configurations sooner or later :)

2020-11-08 01:35 UTC, AndreasMReumschuessel requested changes

2020-11-08 01:35 UTC, AndreasMReumschuessel commented on commands/newsession.js
> +  client.voiceChannels.push(message.guild.channels.cache.get(client.config.secondTeamVc))
Could you also add it to the blank config, please?

2021-04-22 19:04 UTC, stefanleminh commented on commands/newsession.js
> +  client.voiceChannels.push(message.guild.channels.cache.get(client.config.secondTeamVc))
Done!

2021-04-25 16:56 UTC, stefanleminh commented on commands/randomize.js
> +  }
Resolved in revision a20d2f66596e12161ac86cf656e57160db4cfe7e 
Is this how you imagined it?

2021-04-26 18:06 UTC, AndreasMReumschuessel commented on commands/randomize.js
> +  }
Yes!

2021-04-26 18:24 UTC, AndreasMReumschuessel requested changes

2021-04-26 18:24 UTC, AndreasMReumschuessel commented on commands/endmatch.js
> +    console.log(client.voiceChannels[2].members.values())
Is this log statement still needed? If not, remove it.

2021-04-26 20:31 UTC, stefanleminh commented on commands/endmatch.js
> +    console.log(client.voiceChannels[2].members.values())
Resolved in Revision 8a85f36f800986214cbff6dea4076e472d0123d4

2021-04-26 20:32 UTC, merged